#!/bin/bash

# Get system info
USERNAME=$(whoami) 
DATETIME=$(date)
HOSTNAME=$(hostname)
OSINFO=$(source /etc/os-release && echo "$NAME $VERSION")
UPTIME=$(uptime -p)

# Get hardware info
CPU_MODEL=$(lscpu | grep -i 'Model name' | cut -d: -f2 | xargs)
RAM=$(free -h | grep "Mem:" | awk '{print $2}')
DISK=$(df -h --total | grep 'total' | awk '{print $2}')
VIDEO=$(lspci | grep VGA | cut -d: -f3)

# Get network info
FQDN=$(hostname --fqdn)
IP_ADDRESS=$(hostname -I | awk '{print $1}')
GATEWAY_IP=$(ip r | grep default | awk '{print $3}')
DNS_SERVER=$(grep 'nameserver' /etc/resolv.conf | awk '{print $2}' | head -n1)

# Get system status
USERS_LOGGED_IN=$(who | cut -d ' ' -f1 | xargs)
DISK_SPACE=$(df -h / | grep '/' | awk '{print $4}')
PROCESS_COUNT=$(ps -e | wc -l)
LOAD_AVERAGES=$(uptime | awk -F'load average: ' '{print $2}')
MEMORY_ALLOCATION=$(free -h | grep "Mem:" | awk '{print "Total: "$2", Used: "$3", Free: "$4}')

# Output system report
cat <<EOF

System Report generated by $USERNAME, $DATETIME

System Information
------------------
Hostname: $HOSTNAME
OS: $OSINFO
Uptime: $UPTIME

Hardware Information
--------------------
CPU Model: $CPU_MODEL
RAM: $RAM
Disk: $DISK
Video: $VIDEO

Network Information
-------------------
FQDN: $FQDN
IP Address: $IP_ADDRESS
Gateway IP: $GATEWAY_IP
DNS Server: $DNS_SERVER

System Status
-------------
Users Logged In: $USERS_LOGGED_IN
Disk Space: $DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVERAGES
Memory Allocation: $MEMORY_ALLOCATION

EOF
